-- 自动生成：补齐 city_attractions.image_url
-- 先抽查图片是否正确，再在本地 SQL Server 的 travel 数据库执行。

UPDATE dbo.city_attractions SET image_url = 'images/sights/jiamusi/719.webp' WHERE id = 719; -- 佳木斯 / 黑瞎子岛
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiamusi/721.webp' WHERE id = 721; -- 佳木斯 / 三江口
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiamusi/722.webp' WHERE id = 722; -- 佳木斯 / 富锦湿地
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiamusi/724.webp' WHERE id = 724; -- 佳木斯 / 街津口赫哲族村
UPDATE dbo.city_attractions SET image_url = 'images/sights/mudanjiang/731.webp' WHERE id = 731; -- 牡丹江 / 雪乡
UPDATE dbo.city_attractions SET image_url = 'images/sights/mudanjiang/733.webp' WHERE id = 733; -- 牡丹江 / 火山口国家森林公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/mudanjiang/734.webp' WHERE id = 734; -- 牡丹江 / 渤海国遗址
UPDATE dbo.city_attractions SET image_url = 'images/sights/mudanjiang/735.webp' WHERE id = 735; -- 牡丹江 / 横道河子
UPDATE dbo.city_attractions SET image_url = 'images/sights/xuzhou/745.webp' WHERE id = 745; -- 徐州 / 淮海战役纪念塔
UPDATE dbo.city_attractions SET image_url = 'images/sights/xuzhou/746.webp' WHERE id = 746; -- 徐州 / 徐州博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/xuzhou/747.webp' WHERE id = 747; -- 徐州 / 窑湾古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/changzhou/748.webp' WHERE id = 748; -- 常州 / 中华恐龙园
UPDATE dbo.city_attractions SET image_url = 'images/sights/changzhou/749.webp' WHERE id = 749; -- 常州 / 天宁寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/changzhou/750.webp' WHERE id = 750; -- 常州 / 淹城春秋乐园
UPDATE dbo.city_attractions SET image_url = 'images/sights/changzhou/752.webp' WHERE id = 752; -- 常州 / 天目湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/nantong/754.webp' WHERE id = 754; -- 南通 / 狼山
UPDATE dbo.city_attractions SET image_url = 'images/sights/nantong/755.webp' WHERE id = 755; -- 南通 / 濠河风景区
UPDATE dbo.city_attractions SET image_url = 'images/sights/nantong/756.webp' WHERE id = 756; -- 南通 / 南通博物苑
UPDATE dbo.city_attractions SET image_url = 'images/sights/nantong/758.webp' WHERE id = 758; -- 南通 / 水绘园
UPDATE dbo.city_attractions SET image_url = 'images/sights/nantong/759.webp' WHERE id = 759; -- 南通 / 如皋盆景园
UPDATE dbo.city_attractions SET image_url = 'images/sights/lianyungang/761.webp' WHERE id = 761; -- 连云港 / 连岛
UPDATE dbo.city_attractions SET image_url = 'images/sights/lianyungang/762.webp' WHERE id = 762; -- 连云港 / 海州古城
UPDATE dbo.city_attractions SET image_url = 'images/sights/lianyungang/763.webp' WHERE id = 763; -- 连云港 / 渔湾风景区
UPDATE dbo.city_attractions SET image_url = 'images/sights/lianyungang/764.webp' WHERE id = 764; -- 连云港 / 孔望山
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhenjiang/778.webp' WHERE id = 778; -- 镇江 / 金山寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhenjiang/780.webp' WHERE id = 780; -- 镇江 / 焦山
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhenjiang/782.webp' WHERE id = 782; -- 镇江 / 茅山
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhenjiang/783.webp' WHERE id = 783; -- 镇江 / 宝华山
UPDATE dbo.city_attractions SET image_url = 'images/sights/taizhou/784.webp' WHERE id = 784; -- 泰州 / 溱湖国家湿地公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/taizhou/787.webp' WHERE id = 787; -- 泰州 / 凤城河
UPDATE dbo.city_attractions SET image_url = 'images/sights/taizhou/789.webp' WHERE id = 789; -- 泰州 / 乔园
UPDATE dbo.city_attractions SET image_url = 'images/sights/wuhu/797.webp' WHERE id = 797; -- 芜湖 / 鸠兹古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/bangbu/1258.webp' WHERE id = 1258; -- 蚌埠 / 张公山公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/bangbu/1261.webp' WHERE id = 1261; -- 蚌埠 / 三汊河湿地
UPDATE dbo.city_attractions SET image_url = 'images/sights/bangbu/1262.webp' WHERE id = 1262; -- 蚌埠 / 汤和墓古迹园
UPDATE dbo.city_attractions SET image_url = 'images/sights/huainan/802.webp' WHERE id = 802; -- 淮南 / 八公山
UPDATE dbo.city_attractions SET image_url = 'images/sights/huainan/806.webp' WHERE id = 806; -- 淮南 / 上窑山
UPDATE dbo.city_attractions SET image_url = 'images/sights/huainan/807.webp' WHERE id = 807; -- 淮南 / 龙湖公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/maanshan/809.webp' WHERE id = 809; -- 马鞍山 / 李白墓
UPDATE dbo.city_attractions SET image_url = 'images/sights/maanshan/811.webp' WHERE id = 811; -- 马鞍山 / 濮塘风景区
UPDATE dbo.city_attractions SET image_url = 'images/sights/maanshan/812.webp' WHERE id = 812; -- 马鞍山 / 朱然墓
UPDATE dbo.city_attractions SET image_url = 'images/sights/maanshan/813.webp' WHERE id = 813; -- 马鞍山 / 鸡笼山
UPDATE dbo.city_attractions SET image_url = 'images/sights/tongling/821.webp' WHERE id = 821; -- 铜陵 / 永泉山庄
UPDATE dbo.city_attractions SET image_url = 'images/sights/tongling/823.webp' WHERE id = 823; -- 铜陵 / 大通古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/tongling/824.webp' WHERE id = 824; -- 铜陵 / 金牛洞古采矿遗址
UPDATE dbo.city_attractions SET image_url = 'images/sights/tongling/825.webp' WHERE id = 825; -- 铜陵 / 浮山
UPDATE dbo.city_attractions SET image_url = 'images/sights/anqing/1263.webp' WHERE id = 1263; -- 安庆 / 迎江寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/anqing/1264.webp' WHERE id = 1264; -- 安庆 / 振风塔
UPDATE dbo.city_attractions SET image_url = 'images/sights/anqing/1265.webp' WHERE id = 1265; -- 安庆 / 菱湖公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/anqing/1266.webp' WHERE id = 1266; -- 安庆 / 独秀园
UPDATE dbo.city_attractions SET image_url = 'images/sights/anqing/1267.webp' WHERE id = 1267; -- 安庆 / 天柱山
UPDATE dbo.city_attractions SET image_url = 'images/sights/anqing/1268.webp' WHERE id = 1268; -- 安庆 / 桐城六尺巷
UPDATE dbo.city_attractions SET image_url = 'images/sights/huangshan/827.webp' WHERE id = 827; -- 黄山 / 宏村
UPDATE dbo.city_attractions SET image_url = 'images/sights/huangshan/830.webp' WHERE id = 830; -- 黄山 / 屯溪老街
UPDATE dbo.city_attractions SET image_url = 'images/sights/chuzhou/832.webp' WHERE id = 832; -- 滁州 / 琅琊山
UPDATE dbo.city_attractions SET image_url = 'images/sights/chuzhou/835.webp' WHERE id = 835; -- 滁州 / 小岗村
UPDATE dbo.city_attractions SET image_url = 'images/sights/chuzhou/836.webp' WHERE id = 836; -- 滁州 / 韭山洞
UPDATE dbo.city_attractions SET image_url = 'images/sights/chuzhou/837.webp' WHERE id = 837; -- 滁州 / 皇甫山
UPDATE dbo.city_attractions SET image_url = 'images/sights/fuyang/838.webp' WHERE id = 838; -- 阜阳 / 八里河风景区
UPDATE dbo.city_attractions SET image_url = 'images/sights/fuyang/839.webp' WHERE id = 839; -- 阜阳 / 阜阳生态园
UPDATE dbo.city_attractions SET image_url = 'images/sights/fuyang/840.webp' WHERE id = 840; -- 阜阳 / 阜阳博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/fuyang/841.webp' WHERE id = 841; -- 阜阳 / 管仲纪念馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/fuyang/842.webp' WHERE id = 842; -- 阜阳 / 文峰塔
UPDATE dbo.city_attractions SET image_url = 'images/sights/fuyang/843.webp' WHERE id = 843; -- 阜阳 / 颍州西湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/liuan/851.webp' WHERE id = 851; -- 六安 / 万佛湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/liuan/852.webp' WHERE id = 852; -- 六安 / 大别山主峰
UPDATE dbo.city_attractions SET image_url = 'images/sights/liuan/854.webp' WHERE id = 854; -- 六安 / 金寨红军广场
UPDATE dbo.city_attractions SET image_url = 'images/sights/putian/857.webp' WHERE id = 857; -- 莆田 / 南少林寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/putian/858.webp' WHERE id = 858; -- 莆田 / 广化寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/putian/860.webp' WHERE id = 860; -- 莆田 / 菜溪岩
UPDATE dbo.city_attractions SET image_url = 'images/sights/putian/861.webp' WHERE id = 861; -- 莆田 / 木兰陂
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanming/862.webp' WHERE id = 862; -- 三明 / 泰宁大金湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanming/863.webp' WHERE id = 863; -- 三明 / 玉华洞
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanming/864.webp' WHERE id = 864; -- 三明 / 桃源洞
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanming/867.webp' WHERE id = 867; -- 三明 / 上清溪
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhangzhou/868.webp' WHERE id = 868; -- 漳州 / 南靖土楼
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhangzhou/871.webp' WHERE id = 871; -- 漳州 / 漳州古城
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhangzhou/872.webp' WHERE id = 872; -- 漳州 / 火山岛
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhangzhou/873.webp' WHERE id = 873; -- 漳州 / 林语堂纪念馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanping/874.webp' WHERE id = 874; -- 南平 / 武夷山
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanping/875.webp' WHERE id = 875; -- 南平 / 九曲溪
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanping/876.webp' WHERE id = 876; -- 南平 / 大红袍母树
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanping/877.webp' WHERE id = 877; -- 南平 / 下梅古民居
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanping/878.webp' WHERE id = 878; -- 南平 / 和平古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanping/879.webp' WHERE id = 879; -- 南平 / 延平峡阳镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/longyan/880.webp' WHERE id = 880; -- 龙岩 / 永定土楼
UPDATE dbo.city_attractions SET image_url = 'images/sights/longyan/881.webp' WHERE id = 881; -- 龙岩 / 古田会议旧址
UPDATE dbo.city_attractions SET image_url = 'images/sights/longyan/882.webp' WHERE id = 882; -- 龙岩 / 冠豸山
UPDATE dbo.city_attractions SET image_url = 'images/sights/longyan/883.webp' WHERE id = 883; -- 龙岩 / 连城冠豸山
UPDATE dbo.city_attractions SET image_url = 'images/sights/longyan/884.webp' WHERE id = 884; -- 龙岩 / 培田古村落
UPDATE dbo.city_attractions SET image_url = 'images/sights/longyan/885.webp' WHERE id = 885; -- 龙岩 / 龙崆洞
UPDATE dbo.city_attractions SET image_url = 'images/sights/ningde/887.webp' WHERE id = 887; -- 宁德 / 白水洋
UPDATE dbo.city_attractions SET image_url = 'images/sights/ningde/888.webp' WHERE id = 888; -- 宁德 / 霞浦滩涂
UPDATE dbo.city_attractions SET image_url = 'images/sights/ningde/889.webp' WHERE id = 889; -- 宁德 / 三都澳
UPDATE dbo.city_attractions SET image_url = 'images/sights/ningde/891.webp' WHERE id = 891; -- 宁德 / 九龙漈瀑布
UPDATE dbo.city_attractions SET image_url = 'images/sights/jingdezhen/892.webp' WHERE id = 892; -- 景德镇 / 古窑民俗博览区
UPDATE dbo.city_attractions SET image_url = 'images/sights/jingdezhen/893.webp' WHERE id = 893; -- 景德镇 / 陶溪川创意广场
UPDATE dbo.city_attractions SET image_url = 'images/sights/jingdezhen/896.webp' WHERE id = 896; -- 景德镇 / 瑶里古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/jingdezhen/897.webp' WHERE id = 897; -- 景德镇 / 浮梁古县衙
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingxiang/898.webp' WHERE id = 898; -- 萍乡 / 武功山
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingxiang/900.webp' WHERE id = 900; -- 萍乡 / 安源路矿工人运动纪念馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingxiang/902.webp' WHERE id = 902; -- 萍乡 / 杨岐山
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingxiang/903.webp' WHERE id = 903; -- 萍乡 / 仰山
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinyu/904.webp' WHERE id = 904; -- 新余 / 仙女湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinyu/906.webp' WHERE id = 906; -- 新余 / 博迅汽车博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinyu/907.webp' WHERE id = 907; -- 新余 / 昌坊村
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinyu/908.webp' WHERE id = 908; -- 新余 / 孔目江湿地
UPDATE dbo.city_attractions SET image_url = 'images/sights/yingtan/910.webp' WHERE id = 910; -- 鹰潭 / 天师府
UPDATE dbo.city_attractions SET image_url = 'images/sights/yingtan/911.webp' WHERE id = 911; -- 鹰潭 / 上清古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/yingtan/912.webp' WHERE id = 912; -- 鹰潭 / 象鼻山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yingtan/913.webp' WHERE id = 913; -- 鹰潭 / 无蚊村
UPDATE dbo.city_attractions SET image_url = 'images/sights/yingtan/914.webp' WHERE id = 914; -- 鹰潭 / 仙水岩
UPDATE dbo.city_attractions SET image_url = 'images/sights/ganzhou/915.webp' WHERE id = 915; -- 赣州 / 宋城墙
UPDATE dbo.city_attractions SET image_url = 'images/sights/ganzhou/917.webp' WHERE id = 917; -- 赣州 / 郁孤台
UPDATE dbo.city_attractions SET image_url = 'images/sights/ganzhou/918.webp' WHERE id = 918; -- 赣州 / 赣州通天岩
UPDATE dbo.city_attractions SET image_url = 'images/sights/ganzhou/919.webp' WHERE id = 919; -- 赣州 / 瑞金红井
UPDATE dbo.city_attractions SET image_url = 'images/sights/ganzhou/920.webp' WHERE id = 920; -- 赣州 / 三百山
UPDATE dbo.city_attractions SET image_url = 'images/sights/jian/921.webp' WHERE id = 921; -- 吉安 / 井冈山
UPDATE dbo.city_attractions SET image_url = 'images/sights/jian/922.webp' WHERE id = 922; -- 吉安 / 白鹭洲书院
UPDATE dbo.city_attractions SET image_url = 'images/sights/jian/923.webp' WHERE id = 923; -- 吉安 / 渼陂古村
UPDATE dbo.city_attractions SET image_url = 'images/sights/jian/924.webp' WHERE id = 924; -- 吉安 / 富田古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/jian/925.webp' WHERE id = 925; -- 吉安 / 青原山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yichun/927.webp' WHERE id = 927; -- 宜春 / 明月山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yichun/929.webp' WHERE id = 929; -- 宜春 / 宜春鼓楼
UPDATE dbo.city_attractions SET image_url = 'images/sights/yichun/931.webp' WHERE id = 931; -- 宜春 / 三爪仑
UPDATE dbo.city_attractions SET image_url = 'images/sights/yichun/932.webp' WHERE id = 932; -- 宜春 / 靖安中部梦幻城
UPDATE dbo.city_attractions SET image_url = 'images/sights/shangrao/939.webp' WHERE id = 939; -- 上饶 / 三清山
UPDATE dbo.city_attractions SET image_url = 'images/sights/shangrao/941.webp' WHERE id = 941; -- 上饶 / 篁岭晒秋
UPDATE dbo.city_attractions SET image_url = 'images/sights/shangrao/942.webp' WHERE id = 942; -- 上饶 / 龟峰
UPDATE dbo.city_attractions SET image_url = 'images/sights/shangrao/943.webp' WHERE id = 943; -- 上饶 / 鄱阳湖湿地
UPDATE dbo.city_attractions SET image_url = 'images/sights/shangrao/944.webp' WHERE id = 944; -- 上饶 / 鹅湖书院
UPDATE dbo.city_attractions SET image_url = 'images/sights/zibo/946.webp' WHERE id = 946; -- 淄博 / 足球博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/zibo/947.webp' WHERE id = 947; -- 淄博 / 周村古商城
UPDATE dbo.city_attractions SET image_url = 'images/sights/zibo/948.webp' WHERE id = 948; -- 淄博 / 蒲松龄故居
UPDATE dbo.city_attractions SET image_url = 'images/sights/zibo/949.webp' WHERE id = 949; -- 淄博 / 鲁山
UPDATE dbo.city_attractions SET image_url = 'images/sights/zaozhuang/951.webp' WHERE id = 951; -- 枣庄 / 台儿庄古城
UPDATE dbo.city_attractions SET image_url = 'images/sights/zaozhuang/952.webp' WHERE id = 952; -- 枣庄 / 铁道游击队纪念园
UPDATE dbo.city_attractions SET image_url = 'images/sights/zaozhuang/954.webp' WHERE id = 954; -- 枣庄 / 抱犊崮
UPDATE dbo.city_attractions SET image_url = 'images/sights/zaozhuang/955.webp' WHERE id = 955; -- 枣庄 / 冠世榴园
UPDATE dbo.city_attractions SET image_url = 'images/sights/zaozhuang/956.webp' WHERE id = 956; -- 枣庄 / 墨子纪念馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/dongying/957.webp' WHERE id = 957; -- 东营 / 黄河三角洲自然保护区
UPDATE dbo.city_attractions SET image_url = 'images/sights/dongying/958.webp' WHERE id = 958; -- 东营 / 胜利油田
UPDATE dbo.city_attractions SET image_url = 'images/sights/dongying/959.webp' WHERE id = 959; -- 东营 / 黄河口生态旅游区
UPDATE dbo.city_attractions SET image_url = 'images/sights/dongying/960.webp' WHERE id = 960; -- 东营 / 孤岛温泉
UPDATE dbo.city_attractions SET image_url = 'images/sights/dongying/961.webp' WHERE id = 961; -- 东营 / 孙子文化旅游区
UPDATE dbo.city_attractions SET image_url = 'images/sights/taian/974.webp' WHERE id = 974; -- 泰安 / 泰山
UPDATE dbo.city_attractions SET image_url = 'images/sights/taian/975.webp' WHERE id = 975; -- 泰安 / 岱庙
UPDATE dbo.city_attractions SET image_url = 'images/sights/taian/977.webp' WHERE id = 977; -- 泰安 / 徂徕山
UPDATE dbo.city_attractions SET image_url = 'images/sights/taian/978.webp' WHERE id = 978; -- 泰安 / 大汶口遗址
UPDATE dbo.city_attractions SET image_url = 'images/sights/taian/979.webp' WHERE id = 979; -- 泰安 / 东平湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/linyi/986.webp' WHERE id = 986; -- 临沂 / 孟良崮战役纪念馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/linyi/987.webp' WHERE id = 987; -- 临沂 / 沂蒙山
UPDATE dbo.city_attractions SET image_url = 'images/sights/linyi/989.webp' WHERE id = 989; -- 临沂 / 临沂大学
UPDATE dbo.city_attractions SET image_url = 'images/sights/linyi/990.webp' WHERE id = 990; -- 临沂 / 地下大峡谷
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingdingshan/992.webp' WHERE id = 992; -- 平顶山 / 中原大佛
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingdingshan/993.webp' WHERE id = 993; -- 平顶山 / 尧山
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingdingshan/994.webp' WHERE id = 994; -- 平顶山 / 香山寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingdingshan/995.webp' WHERE id = 995; -- 平顶山 / 三苏园
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingdingshan/996.webp' WHERE id = 996; -- 平顶山 / 风穴寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/pingdingshan/997.webp' WHERE id = 997; -- 平顶山 / 白龟湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/anyang/999.webp' WHERE id = 999; -- 安阳 / 红旗渠
UPDATE dbo.city_attractions SET image_url = 'images/sights/anyang/1001.webp' WHERE id = 1001; -- 安阳 / 曹操高陵
UPDATE dbo.city_attractions SET image_url = 'images/sights/anyang/1003.webp' WHERE id = 1003; -- 安阳 / 岳飞庙
UPDATE dbo.city_attractions SET image_url = 'images/sights/hebi/1004.webp' WHERE id = 1004; -- 鹤壁 / 伾山大佛
UPDATE dbo.city_attractions SET image_url = 'images/sights/hebi/1005.webp' WHERE id = 1005; -- 鹤壁 / 云梦山
UPDATE dbo.city_attractions SET image_url = 'images/sights/hebi/1006.webp' WHERE id = 1006; -- 鹤壁 / 朝歌古城
UPDATE dbo.city_attractions SET image_url = 'images/sights/hebi/1007.webp' WHERE id = 1007; -- 鹤壁 / 淇河国家湿地公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/hebi/1008.webp' WHERE id = 1008; -- 鹤壁 / 大石岩
UPDATE dbo.city_attractions SET image_url = 'images/sights/hebi/1009.webp' WHERE id = 1009; -- 鹤壁 / 古灵山
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinxiang/1010.webp' WHERE id = 1010; -- 新乡 / 八里沟
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinxiang/1011.webp' WHERE id = 1011; -- 新乡 / 宝泉旅游度假区
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinxiang/1012.webp' WHERE id = 1012; -- 新乡 / 万仙山
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinxiang/1014.webp' WHERE id = 1014; -- 新乡 / 比干庙
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinxiang/1015.webp' WHERE id = 1015; -- 新乡 / 潞王陵
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiaozuo/1016.webp' WHERE id = 1016; -- 焦作 / 云台山
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiaozuo/1017.webp' WHERE id = 1017; -- 焦作 / 青天河
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiaozuo/1018.webp' WHERE id = 1018; -- 焦作 / 神农山
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiaozuo/1019.webp' WHERE id = 1019; -- 焦作 / 陈家沟
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiaozuo/1020.webp' WHERE id = 1020; -- 焦作 / 圆融寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/jiaozuo/1021.webp' WHERE id = 1021; -- 焦作 / 焦作影视城
UPDATE dbo.city_attractions SET image_url = 'images/sights/puyang/1022.webp' WHERE id = 1022; -- 濮阳 / 戚城文物景区
UPDATE dbo.city_attractions SET image_url = 'images/sights/puyang/1023.webp' WHERE id = 1023; -- 濮阳 / 中华龙源景区
UPDATE dbo.city_attractions SET image_url = 'images/sights/puyang/1024.webp' WHERE id = 1024; -- 濮阳 / 仓颉陵
UPDATE dbo.city_attractions SET image_url = 'images/sights/puyang/1026.webp' WHERE id = 1026; -- 濮阳 / 毛楼生态旅游区
UPDATE dbo.city_attractions SET image_url = 'images/sights/puyang/1027.jpg' WHERE id = 1027; -- 濮阳 / 濮阳水秀
UPDATE dbo.city_attractions SET image_url = 'images/sights/xuchang/1028.webp' WHERE id = 1028; -- 许昌 / 春秋楼
UPDATE dbo.city_attractions SET image_url = 'images/sights/xuchang/1029.webp' WHERE id = 1029; -- 许昌 / 灞陵桥
UPDATE dbo.city_attractions SET image_url = 'images/sights/xuchang/1031.webp' WHERE id = 1031; -- 许昌 / 神垕古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/xuchang/1033.webp' WHERE id = 1033; -- 许昌 / 许昌博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/luohe/1034.webp' WHERE id = 1034; -- 漯河 / 许慎文化园
UPDATE dbo.city_attractions SET image_url = 'images/sights/luohe/1035.webp' WHERE id = 1035; -- 漯河 / 沙澧河风景区
UPDATE dbo.city_attractions SET image_url = 'images/sights/luohe/1036.webp' WHERE id = 1036; -- 漯河 / 小商桥
UPDATE dbo.city_attractions SET image_url = 'images/sights/luohe/1038.webp' WHERE id = 1038; -- 漯河 / 南街村
UPDATE dbo.city_attractions SET image_url = 'images/sights/luohe/1039.webp' WHERE id = 1039; -- 漯河 / 贾湖遗址
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanmenxia/1040.webp' WHERE id = 1040; -- 三门峡 / 黄河三门峡大坝
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanmenxia/1041.webp' WHERE id = 1041; -- 三门峡 / 天鹅湖国家城市湿地公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanmenxia/1042.webp' WHERE id = 1042; -- 三门峡 / 函谷关
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanmenxia/1043.webp' WHERE id = 1043; -- 三门峡 / 虢国博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanmenxia/1044.webp' WHERE id = 1044; -- 三门峡 / 陕州地坑院
UPDATE dbo.city_attractions SET image_url = 'images/sights/sanmenxia/1045.webp' WHERE id = 1045; -- 三门峡 / 仰韶文化遗址
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinyang/1058.webp' WHERE id = 1058; -- 信阳 / 南湾湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinyang/1060.webp' WHERE id = 1060; -- 信阳 / 灵山寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinyang/1062.webp' WHERE id = 1062; -- 信阳 / 郝家冲村
UPDATE dbo.city_attractions SET image_url = 'images/sights/xinyang/1063.webp' WHERE id = 1063; -- 信阳 / 西九华山
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhuzhou/1071.webp' WHERE id = 1071; -- 株洲 / 神农谷
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhuzhou/1072.webp' WHERE id = 1072; -- 株洲 / 云阳山
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhuzhou/1075.webp' WHERE id = 1075; -- 株洲 / 湘江风光带
UPDATE dbo.city_attractions SET image_url = 'images/sights/xiangtan/1076.webp' WHERE id = 1076; -- 湘潭 / 韶山毛泽东故居
UPDATE dbo.city_attractions SET image_url = 'images/sights/xiangtan/1077.webp' WHERE id = 1077; -- 湘潭 / 彭德怀纪念馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/xiangtan/1079.webp' WHERE id = 1079; -- 湘潭 / 昭山
UPDATE dbo.city_attractions SET image_url = 'images/sights/xiangtan/1080.webp' WHERE id = 1080; -- 湘潭 / 窑湾老街
UPDATE dbo.city_attractions SET image_url = 'images/sights/hengyang/1082.webp' WHERE id = 1082; -- 衡阳 / 南岳衡山
UPDATE dbo.city_attractions SET image_url = 'images/sights/hengyang/1084.webp' WHERE id = 1084; -- 衡阳 / 石鼓书院
UPDATE dbo.city_attractions SET image_url = 'images/sights/hengyang/1085.webp' WHERE id = 1085; -- 衡阳 / 蔡伦竹海
UPDATE dbo.city_attractions SET image_url = 'images/sights/hengyang/1087.webp' WHERE id = 1087; -- 衡阳 / 回雁峰
UPDATE dbo.city_attractions SET image_url = 'images/sights/changde/1100.webp' WHERE id = 1100; -- 常德 / 桃花源
UPDATE dbo.city_attractions SET image_url = 'images/sights/changde/1101.webp' WHERE id = 1101; -- 常德 / 柳叶湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/changde/1103.webp' WHERE id = 1103; -- 常德 / 城头山遗址
UPDATE dbo.city_attractions SET image_url = 'images/sights/changde/1104.webp' WHERE id = 1104; -- 常德 / 壶瓶山
UPDATE dbo.city_attractions SET image_url = 'images/sights/changde/1105.webp' WHERE id = 1105; -- 常德 / 夹山寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/chenzhou/1112.webp' WHERE id = 1112; -- 郴州 / 东江湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/chenzhou/1113.webp' WHERE id = 1113; -- 郴州 / 莽山国家森林公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/chenzhou/1114.webp' WHERE id = 1114; -- 郴州 / 苏仙岭
UPDATE dbo.city_attractions SET image_url = 'images/sights/chenzhou/1115.webp' WHERE id = 1115; -- 郴州 / 万华岩
UPDATE dbo.city_attractions SET image_url = 'images/sights/chenzhou/1116.webp' WHERE id = 1116; -- 郴州 / 仰天湖草原
UPDATE dbo.city_attractions SET image_url = 'images/sights/chenzhou/1117.webp' WHERE id = 1117; -- 郴州 / 汝城温泉
UPDATE dbo.city_attractions SET image_url = 'images/sights/yongzhou/1118.webp' WHERE id = 1118; -- 永州 / 阳明山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yongzhou/1119.webp' WHERE id = 1119; -- 永州 / 九嶷山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yongzhou/1121.webp' WHERE id = 1121; -- 永州 / 永州八景
UPDATE dbo.city_attractions SET image_url = 'images/sights/yongzhou/1122.webp' WHERE id = 1122; -- 永州 / 江永女书园
UPDATE dbo.city_attractions SET image_url = 'images/sights/yongzhou/1123.webp' WHERE id = 1123; -- 永州 / 舜帝陵
UPDATE dbo.city_attractions SET image_url = 'images/sights/huaihua/1124.webp' WHERE id = 1124; -- 怀化 / 洪江古商城
UPDATE dbo.city_attractions SET image_url = 'images/sights/huaihua/1125.webp' WHERE id = 1125; -- 怀化 / 芷江受降纪念坊
UPDATE dbo.city_attractions SET image_url = 'images/sights/huaihua/1126.webp' WHERE id = 1126; -- 怀化 / 黔阳古城
UPDATE dbo.city_attractions SET image_url = 'images/sights/huaihua/1128.webp' WHERE id = 1128; -- 怀化 / 皇都侗寨
UPDATE dbo.city_attractions SET image_url = 'images/sights/wuzhou/1137.webp' WHERE id = 1137; -- 梧州 / 龙母庙
UPDATE dbo.city_attractions SET image_url = 'images/sights/wuzhou/1138.webp' WHERE id = 1138; -- 梧州 / 西江明珠塔
UPDATE dbo.city_attractions SET image_url = 'images/sights/wuzhou/1139.webp' WHERE id = 1139; -- 梧州 / 白云山
UPDATE dbo.city_attractions SET image_url = 'images/sights/wuzhou/1140.jpg' WHERE id = 1140; -- 梧州 / 藤县石表山
UPDATE dbo.city_attractions SET image_url = 'images/sights/wuzhou/1141.webp' WHERE id = 1141; -- 梧州 / 太平天国封王遗址
UPDATE dbo.city_attractions SET image_url = 'images/sights/fangchenggang/1142.webp' WHERE id = 1142; -- 防城港 / 万尾金滩
UPDATE dbo.city_attractions SET image_url = 'images/sights/fangchenggang/1143.webp' WHERE id = 1143; -- 防城港 / 江山半岛
UPDATE dbo.city_attractions SET image_url = 'images/sights/fangchenggang/1144.webp' WHERE id = 1144; -- 防城港 / 白浪滩
UPDATE dbo.city_attractions SET image_url = 'images/sights/fangchenggang/1145.webp' WHERE id = 1145; -- 防城港 / 东兴国门
UPDATE dbo.city_attractions SET image_url = 'images/sights/fangchenggang/1146.webp' WHERE id = 1146; -- 防城港 / 京族哈亭
UPDATE dbo.city_attractions SET image_url = 'images/sights/fangchenggang/1147.webp' WHERE id = 1147; -- 防城港 / 十万大山森林公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/qinzhou/1148.webp' WHERE id = 1148; -- 钦州 / 三娘湾
UPDATE dbo.city_attractions SET image_url = 'images/sights/qinzhou/1150.webp' WHERE id = 1150; -- 钦州 / 刘永福故居
UPDATE dbo.city_attractions SET image_url = 'images/sights/qinzhou/1151.webp' WHERE id = 1151; -- 钦州 / 冯子材故居
UPDATE dbo.city_attractions SET image_url = 'images/sights/qinzhou/1152.webp' WHERE id = 1152; -- 钦州 / 钦州坭兴陶艺术馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/guigang/1154.webp' WHERE id = 1154; -- 贵港 / 南山寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/guigang/1155.webp' WHERE id = 1155; -- 贵港 / 桂平西山
UPDATE dbo.city_attractions SET image_url = 'images/sights/guigang/1156.webp' WHERE id = 1156; -- 贵港 / 龙潭国家森林公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/guigang/1157.webp' WHERE id = 1157; -- 贵港 / 平天山
UPDATE dbo.city_attractions SET image_url = 'images/sights/guigang/1158.webp' WHERE id = 1158; -- 贵港 / 荷城广场
UPDATE dbo.city_attractions SET image_url = 'images/sights/yulin/1160.webp' WHERE id = 1160; -- 玉林 / 云天文化城
UPDATE dbo.city_attractions SET image_url = 'images/sights/yulin/1162.webp' WHERE id = 1162; -- 玉林 / 大容山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yulin/1163.webp' WHERE id = 1163; -- 玉林 / 都峤山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yulin/1164.webp' WHERE id = 1164; -- 玉林 / 谢鲁山庄
UPDATE dbo.city_attractions SET image_url = 'images/sights/yulin/1165.webp' WHERE id = 1165; -- 玉林 / 龙珠湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/baise/1166.webp' WHERE id = 1166; -- 百色 / 通灵大峡谷
UPDATE dbo.city_attractions SET image_url = 'images/sights/baise/1168.webp' WHERE id = 1168; -- 百色 / 百色起义纪念馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/baise/1169.webp' WHERE id = 1169; -- 百色 / 右江民族博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/baise/1170.webp' WHERE id = 1170; -- 百色 / 澄碧湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/hezhou/1172.webp' WHERE id = 1172; -- 贺州 / 黄姚古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/hezhou/1173.webp' WHERE id = 1173; -- 贺州 / 姑婆山
UPDATE dbo.city_attractions SET image_url = 'images/sights/hezhou/1174.webp' WHERE id = 1174; -- 贺州 / 十八水
UPDATE dbo.city_attractions SET image_url = 'images/sights/hezhou/1175.webp' WHERE id = 1175; -- 贺州 / 紫云洞
UPDATE dbo.city_attractions SET image_url = 'images/sights/hezhou/1176.webp' WHERE id = 1176; -- 贺州 / 玉石林
UPDATE dbo.city_attractions SET image_url = 'images/sights/hezhou/1177.webp' WHERE id = 1177; -- 贺州 / 秀水状元村
UPDATE dbo.city_attractions SET image_url = 'images/sights/zigong/1269.webp' WHERE id = 1269; -- 自贡 / 自贡恐龙博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/zigong/1270.webp' WHERE id = 1270; -- 自贡 / 盐业历史博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/zigong/1272.webp' WHERE id = 1272; -- 自贡 / 彩灯大世界
UPDATE dbo.city_attractions SET image_url = 'images/sights/zigong/1273.webp' WHERE id = 1273; -- 自贡 / 仙市古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/luzhou/1279.webp' WHERE id = 1279; -- 泸州 / 泸州老窖博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/luzhou/1281.webp' WHERE id = 1281; -- 泸州 / 方山风景区
UPDATE dbo.city_attractions SET image_url = 'images/sights/luzhou/1282.webp' WHERE id = 1282; -- 泸州 / 尧坝古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/luzhou/1283.webp' WHERE id = 1283; -- 泸州 / 报恩塔
UPDATE dbo.city_attractions SET image_url = 'images/sights/deyang/1284.webp' WHERE id = 1284; -- 德阳 / 三星堆博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/deyang/1286.webp' WHERE id = 1286; -- 德阳 / 绵竹年画村
UPDATE dbo.city_attractions SET image_url = 'images/sights/deyang/1287.webp' WHERE id = 1287; -- 德阳 / 孝泉古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/deyang/1288.webp' WHERE id = 1288; -- 德阳 / 白马关
UPDATE dbo.city_attractions SET image_url = 'images/sights/mianyang/1289.webp' WHERE id = 1289; -- 绵阳 / 越王楼
UPDATE dbo.city_attractions SET image_url = 'images/sights/mianyang/1290.webp' WHERE id = 1290; -- 绵阳 / 绵阳科技馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/mianyang/1291.webp' WHERE id = 1291; -- 绵阳 / 富乐山
UPDATE dbo.city_attractions SET image_url = 'images/sights/mianyang/1292.webp' WHERE id = 1292; -- 绵阳 / 李白故里
UPDATE dbo.city_attractions SET image_url = 'images/sights/mianyang/1293.webp' WHERE id = 1293; -- 绵阳 / 窦圌山
UPDATE dbo.city_attractions SET image_url = 'images/sights/mianyang/1294.webp' WHERE id = 1294; -- 绵阳 / 仙海湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangyuan/1295.webp' WHERE id = 1295; -- 广元 / 剑门关
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangyuan/1296.webp' WHERE id = 1296; -- 广元 / 千佛崖
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangyuan/1297.webp' WHERE id = 1297; -- 广元 / 昭化古城
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangyuan/1298.webp' WHERE id = 1298; -- 广元 / 皇泽寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangyuan/1299.webp' WHERE id = 1299; -- 广元 / 明月峡
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangyuan/1300.webp' WHERE id = 1300; -- 广元 / 唐家河自然保护区
UPDATE dbo.city_attractions SET image_url = 'images/sights/neijiang/1306.webp' WHERE id = 1306; -- 内江 / 张大千纪念馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/neijiang/1307.webp' WHERE id = 1307; -- 内江 / 圣水寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/neijiang/1308.webp' WHERE id = 1308; -- 内江 / 隆昌石牌坊群
UPDATE dbo.city_attractions SET image_url = 'images/sights/neijiang/1309.webp' WHERE id = 1309; -- 内江 / 资中重龙山
UPDATE dbo.city_attractions SET image_url = 'images/sights/neijiang/1310.webp' WHERE id = 1310; -- 内江 / 大千园
UPDATE dbo.city_attractions SET image_url = 'images/sights/leshan/1312.webp' WHERE id = 1312; -- 乐山 / 峨眉山
UPDATE dbo.city_attractions SET image_url = 'images/sights/leshan/1313.webp' WHERE id = 1313; -- 乐山 / 嘉定坊
UPDATE dbo.city_attractions SET image_url = 'images/sights/leshan/1314.webp' WHERE id = 1314; -- 乐山 / 乌尤寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/leshan/1315.webp' WHERE id = 1315; -- 乐山 / 夹江千佛岩
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanchong/1316.webp' WHERE id = 1316; -- 南充 / 阆中古城
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanchong/1318.webp' WHERE id = 1318; -- 南充 / 张澜故居
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanchong/1319.webp' WHERE id = 1319; -- 南充 / 朱德故里
UPDATE dbo.city_attractions SET image_url = 'images/sights/nanchong/1320.webp' WHERE id = 1320; -- 南充 / 凌云山
UPDATE dbo.city_attractions SET image_url = 'images/sights/meishan/1322.webp' WHERE id = 1322; -- 眉山 / 三苏祠
UPDATE dbo.city_attractions SET image_url = 'images/sights/meishan/1324.webp' WHERE id = 1324; -- 眉山 / 柳江古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/meishan/1325.webp' WHERE id = 1325; -- 眉山 / 彭祖山
UPDATE dbo.city_attractions SET image_url = 'images/sights/meishan/1326.webp' WHERE id = 1326; -- 眉山 / 黑龙滩
UPDATE dbo.city_attractions SET image_url = 'images/sights/meishan/1327.webp' WHERE id = 1327; -- 眉山 / 青神中岩寺
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangan/1333.webp' WHERE id = 1333; -- 广安 / 邓小平故里
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangan/1334.webp' WHERE id = 1334; -- 广安 / 华蓥山
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangan/1335.webp' WHERE id = 1335; -- 广安 / 宝箴塞
UPDATE dbo.city_attractions SET image_url = 'images/sights/guangan/1337.webp' WHERE id = 1337; -- 广安 / 天意谷
UPDATE dbo.city_attractions SET image_url = 'images/sights/dazhou/1338.webp' WHERE id = 1338; -- 达州 / 真佛山
UPDATE dbo.city_attractions SET image_url = 'images/sights/dazhou/1339.webp' WHERE id = 1339; -- 达州 / 巴山大峡谷
UPDATE dbo.city_attractions SET image_url = 'images/sights/dazhou/1340.webp' WHERE id = 1340; -- 达州 / 渠县賨人谷
UPDATE dbo.city_attractions SET image_url = 'images/sights/dazhou/1341.webp' WHERE id = 1341; -- 达州 / 达州凤凰山
UPDATE dbo.city_attractions SET image_url = 'images/sights/dazhou/1342.webp' WHERE id = 1342; -- 达州 / 红军烈士陵园
UPDATE dbo.city_attractions SET image_url = 'images/sights/yaan/1343.webp' WHERE id = 1343; -- 雅安 / 碧峰峡
UPDATE dbo.city_attractions SET image_url = 'images/sights/yaan/1344.webp' WHERE id = 1344; -- 雅安 / 上里古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/yaan/1345.webp' WHERE id = 1345; -- 雅安 / 蒙顶山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yaan/1346.webp' WHERE id = 1346; -- 雅安 / 牛背山
UPDATE dbo.city_attractions SET image_url = 'images/sights/yaan/1347.webp' WHERE id = 1347; -- 雅安 / 夹金山
UPDATE dbo.city_attractions SET image_url = 'images/sights/liupanshui/1350.webp' WHERE id = 1350; -- 六盘水 / 牂牁江
UPDATE dbo.city_attractions SET image_url = 'images/sights/liupanshui/1351.webp' WHERE id = 1351; -- 六盘水 / 玉舍国家森林公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/liupanshui/1352.webp' WHERE id = 1352; -- 六盘水 / 哒啦仙谷
UPDATE dbo.city_attractions SET image_url = 'images/sights/liupanshui/1353.webp' WHERE id = 1353; -- 六盘水 / 水城古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/zunyi/1354.webp' WHERE id = 1354; -- 遵义 / 遵义会议会址
UPDATE dbo.city_attractions SET image_url = 'images/sights/zunyi/1355.webp' WHERE id = 1355; -- 遵义 / 赤水丹霞
UPDATE dbo.city_attractions SET image_url = 'images/sights/zunyi/1356.webp' WHERE id = 1356; -- 遵义 / 茅台镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/zunyi/1358.webp' WHERE id = 1358; -- 遵义 / 娄山关
UPDATE dbo.city_attractions SET image_url = 'images/sights/zunyi/1359.jpg' WHERE id = 1359; -- 遵义 / 丙安古镇
UPDATE dbo.city_attractions SET image_url = 'images/sights/anshun/1360.webp' WHERE id = 1360; -- 安顺 / 黄果树瀑布
UPDATE dbo.city_attractions SET image_url = 'images/sights/anshun/1362.webp' WHERE id = 1362; -- 安顺 / 天龙屯堡
UPDATE dbo.city_attractions SET image_url = 'images/sights/anshun/1363.webp' WHERE id = 1363; -- 安顺 / 安顺文庙
UPDATE dbo.city_attractions SET image_url = 'images/sights/anshun/1365.webp' WHERE id = 1365; -- 安顺 / 花江大峡谷
UPDATE dbo.city_attractions SET image_url = 'images/sights/bijie/1366.webp' WHERE id = 1366; -- 毕节 / 百里杜鹃
UPDATE dbo.city_attractions SET image_url = 'images/sights/bijie/1367.webp' WHERE id = 1367; -- 毕节 / 织金洞
UPDATE dbo.city_attractions SET image_url = 'images/sights/bijie/1368.webp' WHERE id = 1368; -- 毕节 / 威宁草海
UPDATE dbo.city_attractions SET image_url = 'images/sights/bijie/1370.webp' WHERE id = 1370; -- 毕节 / 总溪河
UPDATE dbo.city_attractions SET image_url = 'images/sights/bijie/1371.webp' WHERE id = 1371; -- 毕节 / 九洞天
UPDATE dbo.city_attractions SET image_url = 'images/sights/qujing/1372.webp' WHERE id = 1372; -- 曲靖 / 珠江源
UPDATE dbo.city_attractions SET image_url = 'images/sights/qujing/1373.webp' WHERE id = 1373; -- 曲靖 / 九龙瀑布群
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhaotong/1387.webp' WHERE id = 1387; -- 昭通 / 大山包国家公园
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhaotong/1388.webp' WHERE id = 1388; -- 昭通 / 盐津豆沙关
UPDATE dbo.city_attractions SET image_url = 'images/sights/zhaotong/1389.webp' WHERE id = 1389; -- 昭通 / 大关黄连河
UPDATE dbo.city_attractions SET image_url = 'images/sights/shizuishan/1491.webp' WHERE id = 1491; -- 石嘴山 / 沙湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/shizuishan/1492.webp' WHERE id = 1492; -- 石嘴山 / 贺兰山岩画
UPDATE dbo.city_attractions SET image_url = 'images/sights/shizuishan/1493.webp' WHERE id = 1493; -- 石嘴山 / 北武当庙
UPDATE dbo.city_attractions SET image_url = 'images/sights/shizuishan/1495.webp' WHERE id = 1495; -- 石嘴山 / 星海湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/tulufan/1511.jpg' WHERE id = 1511; -- 吐鲁番 / 火焰山
UPDATE dbo.city_attractions SET image_url = 'images/sights/tulufan/1513.webp' WHERE id = 1513; -- 吐鲁番 / 葡萄沟
UPDATE dbo.city_attractions SET image_url = 'images/sights/tulufan/1514.webp' WHERE id = 1514; -- 吐鲁番 / 交河故城
UPDATE dbo.city_attractions SET image_url = 'images/sights/tulufan/1516.webp' WHERE id = 1516; -- 吐鲁番 / 吐峪沟
UPDATE dbo.city_attractions SET image_url = 'images/sights/madrid/1548.jpg' WHERE id = 1548; -- 马德里 / 普拉多博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/madrid/1550.webp' WHERE id = 1550; -- 马德里 / 伯纳乌球场
UPDATE dbo.city_attractions SET image_url = 'images/sights/lisbon/1552.webp' WHERE id = 1552; -- 里斯本 / 贝伦塔
UPDATE dbo.city_attractions SET image_url = 'images/sights/lisbon/1554.webp' WHERE id = 1554; -- 里斯本 / 航海纪念碑
UPDATE dbo.city_attractions SET image_url = 'images/sights/lisbon/1556.webp' WHERE id = 1556; -- 里斯本 / 阿尔法玛老城
UPDATE dbo.city_attractions SET image_url = 'images/sights/stockholm/1579.webp' WHERE id = 1579; -- 斯德哥尔摩 / 瓦萨沉船博物馆
UPDATE dbo.city_attractions SET image_url = 'images/sights/stockholm/1580.webp' WHERE id = 1580; -- 斯德哥尔摩 / 斯德哥尔摩老城
UPDATE dbo.city_attractions SET image_url = 'images/sights/stockholm/1582.webp' WHERE id = 1582; -- 斯德哥尔摩 / 市政厅
UPDATE dbo.city_attractions SET image_url = 'images/sights/stockholm/1584.webp' WHERE id = 1584; -- 斯德哥尔摩 / 湖心岛
UPDATE dbo.city_attractions SET image_url = 'images/sights/moscow/1597.webp' WHERE id = 1597; -- 莫斯科 / 红场
UPDATE dbo.city_attractions SET image_url = 'images/sights/moscow/1599.webp' WHERE id = 1599; -- 莫斯科 / 圣瓦西里大教堂
UPDATE dbo.city_attractions SET image_url = 'images/sights/moscow/1601.webp' WHERE id = 1601; -- 莫斯科 / 阿尔巴特街
UPDATE dbo.city_attractions SET image_url = 'images/sights/zurich/1603.webp' WHERE id = 1603; -- 苏黎世 / 苏黎世湖
UPDATE dbo.city_attractions SET image_url = 'images/sights/zurich/1605.webp' WHERE id = 1605; -- 苏黎世 / 苏黎世大教堂
UPDATE dbo.city_attractions SET image_url = 'images/sights/zurich/1607.webp' WHERE id = 1607; -- 苏黎世 / 利马特河
UPDATE dbo.city_attractions SET image_url = 'images/sights/pujidao/1190.webp' WHERE id = 1190; -- 普吉岛 / 芭东海滩
UPDATE dbo.city_attractions SET image_url = 'images/sights/pujidao/1191.webp' WHERE id = 1191; -- 普吉岛 / 皮皮岛
UPDATE dbo.city_attractions SET image_url = 'images/sights/amusitedan/1196.webp' WHERE id = 1196; -- 阿姆斯特丹 / 运河区
UPDATE dbo.city_attractions SET image_url = 'images/sights/amusitedan/1198.webp' WHERE id = 1198; -- 阿姆斯特丹 / 风车村
UPDATE dbo.city_attractions SET image_url = 'images/sights/liyuereneilu/1202.webp' WHERE id = 1202; -- 里约热内卢 / 基督像
UPDATE dbo.city_attractions SET image_url = 'images/sights/liyuereneilu/1204.webp' WHERE id = 1204; -- 里约热内卢 / 糖面包山